#!C:\Users\sagar\OneDrive\Documents\EnglishToGerman-1\virtualEnv\Scripts\python.exe
# -*- coding: UTF-8 -*-
from __future__ import print_function, division, absolute_import

from numba.misc.numba_entry import main

if __name__ == "__main__":
    main()
